services:
  backend:
    build:
      context: backend
      target: builder
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    user: ${DB_USER}
    hostname: ${DB_HOST}
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_SECRET}
    expose:
      - ${DB_PORT}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  db-data:
